stages:
  - build
  - test
  - deploy

before_script:
  - 'nuget restore'

build:
 stage: build
 script:
  - 'msbuild /t:Clean,ReBuild /p:Configuration=Debug;Platform="Any CPU"'
  - 'msbuild /t:ReBuild /p:Configuration=Release;Platform="Any CPU"'
 artifacts:
   paths:
   - bin/
   - packages/
 only:
   - master

test:
 stage: test
 script:
  - ./packages/xunit.runner.console.2.4.0-beta.1.build3958/tools/net452/xunit.console.exe ./bin/Windows/x86/Debug/Upp.Net.IntegrationTests.dll
  - ./packages/xunit.runner.console.2.4.0-beta.1.build3958/tools/net452/xunit.console.exe ./bin/Windows/x86/Debug/Upp.Net.UnitTests.dll
 dependencies:
  - build

deploy:
 stage: deploy
 script:
  - echo $CI_BUILD_ID
  - echo $CI_PIPELINE_ID
  - echo $CI_SERVER
  - echo $GITLAB_CI
  - nuget pack -Version $CI_PIPELINE_ID
  - nuget add *.nupkg -source /mnt/nuget/
 dependencies:
  - build